name: Trigger Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:


# FrontEnd Team
# "TaskTypesTitle":"FE-CreatUI,FE-Review,FE-APIIntegration,FE-ReviewStory"
# Backend Team
# "TaskTypesTitle":"[BE][Supplier][Design],[BE] [Supplier][Implementation],[BE] [Supplier][UnitTest],[BE] [Supplier][Review]"
# Testing Team
# "TaskTypesTitle": "Test Analysis,Test Case Preparation,Test Execution"
# for Task
      - name: Create Task Creation Automation Inputs JSON
        run: |
          echo '{
            "ref": "master",
            "inputs": {
                "AzureToken": "${{ secrets.AZURE_PAT }}",
                "Organization": "GSIntegrationTeam",
                "ProjectName": "Scrap%20Management",
                "ActivateAutoClose": false,
                "TaskTypesTitle":"[BE][Supplier][Design],[BE] [Supplier][Implementation],[BE] [Supplier][UnitTest],[BE] [Supplier][Review]"
            }
          }' > TaskCreationAutomation.json
          
      - name: Task Creation Automation
        run: |
          curl --location 'https://api.github.com/repos/MohamedAbdelrehem/AzureTaskAutomate/actions/workflows/Actions_Schedule_check_updates.yml/dispatches' \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.privateRepoAuth }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --header 'Content-Type: application/json' \
          --data @TaskCreationAutomation.json

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
 # for Analysis
      # - name: Create Analysis Automation Inputs JSON
      #   run: |
      #     echo '{
      #       "ref": "master",
      #       "inputs": {
      #           "AzureToken": "${{ secrets.AZURE_PAT }}",
      #           "Organization": "GSIntegrationTeam",
      #           "ProjectName": "Scrap%20Management",
      #           "POName": "Ahmed Hisham",
      #           "FrontEndIDs": "b74e0bb1-49f3-65af-9283-849b2e350002",
      #           "BackEndIDs": "51625031-41e2-6ab0-9da1-c5ce45615271",
      #           "MobileIDs": "1436548a-4c9a-6ba8-ad22-8aa503fd959b",
      #           "StateReflectKeyword": "Ready For Review"
      #       }
      #     }' > AnalysisAutomation.json

      # - name: Analysis Automation
      #   run: |
      #     curl --location 'https://api.github.com/repos/MohamedAbdelrehem/AzureAnalysisAutomate/actions/workflows/Actions_Schedule_check_updates.yml/dispatches' \
      #     --header 'Accept: application/vnd.github+json' \
      #     --header 'Authorization: Bearer ${{ secrets.privateRepoAuth }}' \
      #     --header 'X-GitHub-Api-Version: 2022-11-28' \
      #     --header 'Content-Type: application/json' \
      #     --data @AnalysisAutomation.json
